protos:
  - repository: "protos"
    tag: ""
    proto_folder: "store"
    merge: false
    modules:
      - "store"
    black_list: []
    custom:
      ".": "#[derive(serde_derive::Deserialize, serde_derive::Serialize)]"
