// This file is @generated by prost-build.
/// PoolParams defined the parameters that will be managed by the pool
/// governance in the future. This params are not managed by the chain
/// governance. Instead they will be managed by the token holders of the pool.
/// The pool's token holders are specified in future_pool_governor.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolParams {
    #[prost(string, tag = "1")]
    pub swap_fee: ::prost::alloc::string::String,
    /// N.B.: exit fee is disabled during pool creation in x/poolmanager. While old
    /// pools can maintain a non-zero fee. No new pool can be created with non-zero
    /// fee anymore
    #[prost(string, tag = "2")]
    pub exit_fee: ::prost::alloc::string::String,
}
impl ::prost::Name for PoolParams {
    const NAME: &'static str = "PoolParams";
    const PACKAGE: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "osmosis.gamm.poolmodels.stableswap.v1beta1.PoolParams".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/osmosis.gamm.poolmodels.stableswap.v1beta1.PoolParams".into()
    }
}
/// Pool is the stableswap Pool struct
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pool {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub id: u64,
    #[prost(message, optional, tag = "3")]
    pub pool_params: ::core::option::Option<PoolParams>,
    /// This string specifies who will govern the pool in the future.
    /// Valid forms of this are:
    /// {token name},{duration}
    /// {duration}
    /// where {token name} if specified is the token which determines the
    /// governor, and if not specified is the LP token for this pool.duration is
    /// a time specified as 0w,1w,2w, etc. which specifies how long the token
    /// would need to be locked up to count in governance. 0w means no lockup.
    #[prost(string, tag = "4")]
    pub future_pool_governor: ::prost::alloc::string::String,
    /// sum of all LP shares
    #[prost(message, optional, tag = "5")]
    pub total_shares: ::core::option::Option<
        super::super::super::super::super::cosmos::base::v1beta1::Coin,
    >,
    /// assets in the pool
    #[prost(message, repeated, tag = "6")]
    pub pool_liquidity: ::prost::alloc::vec::Vec<
        super::super::super::super::super::cosmos::base::v1beta1::Coin,
    >,
    /// for calculation amognst assets with different precisions
    #[prost(uint64, repeated, packed = "false", tag = "7")]
    pub scaling_factors: ::prost::alloc::vec::Vec<u64>,
    /// scaling_factor_controller is the address can adjust pool scaling factors
    #[prost(string, tag = "8")]
    pub scaling_factor_controller: ::prost::alloc::string::String,
}
impl ::prost::Name for Pool {
    const NAME: &'static str = "Pool";
    const PACKAGE: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "osmosis.gamm.poolmodels.stableswap.v1beta1.Pool".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/osmosis.gamm.poolmodels.stableswap.v1beta1.Pool".into()
    }
}
/// ===================== MsgCreatePool
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateStableswapPool {
    #[prost(string, tag = "1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub pool_params: ::core::option::Option<PoolParams>,
    #[prost(message, repeated, tag = "3")]
    pub initial_pool_liquidity: ::prost::alloc::vec::Vec<
        super::super::super::super::super::cosmos::base::v1beta1::Coin,
    >,
    #[prost(uint64, repeated, packed = "false", tag = "4")]
    pub scaling_factors: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "5")]
    pub future_pool_governor: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub scaling_factor_controller: ::prost::alloc::string::String,
}
impl ::prost::Name for MsgCreateStableswapPool {
    const NAME: &'static str = "MsgCreateStableswapPool";
    const PACKAGE: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPool".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPool".into()
    }
}
/// Returns a poolID with custom poolName.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateStableswapPoolResponse {
    #[prost(uint64, tag = "1")]
    pub pool_id: u64,
}
impl ::prost::Name for MsgCreateStableswapPoolResponse {
    const NAME: &'static str = "MsgCreateStableswapPoolResponse";
    const PACKAGE: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPoolResponse"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPoolResponse"
            .into()
    }
}
/// Sender must be the pool's scaling_factor_governor in order for the tx to
/// succeed. Adjusts stableswap scaling factors.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgStableSwapAdjustScalingFactors {
    #[prost(string, tag = "1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub pool_id: u64,
    #[prost(uint64, repeated, packed = "false", tag = "3")]
    pub scaling_factors: ::prost::alloc::vec::Vec<u64>,
}
impl ::prost::Name for MsgStableSwapAdjustScalingFactors {
    const NAME: &'static str = "MsgStableSwapAdjustScalingFactors";
    const PACKAGE: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactors"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactors"
            .into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgStableSwapAdjustScalingFactorsResponse {}
impl ::prost::Name for MsgStableSwapAdjustScalingFactorsResponse {
    const NAME: &'static str = "MsgStableSwapAdjustScalingFactorsResponse";
    const PACKAGE: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactorsResponse"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactorsResponse"
            .into()
    }
}
/// Generated client implementations.
#[cfg(feature = "osmosis")]
pub mod msg_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            MsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_stableswap_pool(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgCreateStableswapPool>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreateStableswapPoolResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/osmosis.gamm.poolmodels.stableswap.v1beta1.Msg/CreateStableswapPool",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "osmosis.gamm.poolmodels.stableswap.v1beta1.Msg",
                        "CreateStableswapPool",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn stable_swap_adjust_scaling_factors(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgStableSwapAdjustScalingFactors>,
        ) -> std::result::Result<
            tonic::Response<super::MsgStableSwapAdjustScalingFactorsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/osmosis.gamm.poolmodels.stableswap.v1beta1.Msg/StableSwapAdjustScalingFactors",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "osmosis.gamm.poolmodels.stableswap.v1beta1.Msg",
                        "StableSwapAdjustScalingFactors",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "osmosis")]
pub mod msg_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MsgServer.
    #[async_trait]
    pub trait Msg: Send + Sync + 'static {
        async fn create_stableswap_pool(
            &self,
            request: tonic::Request<super::MsgCreateStableswapPool>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreateStableswapPoolResponse>,
            tonic::Status,
        >;
        async fn stable_swap_adjust_scaling_factors(
            &self,
            request: tonic::Request<super::MsgStableSwapAdjustScalingFactors>,
        ) -> std::result::Result<
            tonic::Response<super::MsgStableSwapAdjustScalingFactorsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MsgServer<T: Msg> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: Msg> MsgServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MsgServer<T>
    where
        T: Msg,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/osmosis.gamm.poolmodels.stableswap.v1beta1.Msg/CreateStableswapPool" => {
                    #[allow(non_camel_case_types)]
                    struct CreateStableswapPoolSvc<T: Msg>(pub Arc<T>);
                    impl<
                        T: Msg,
                    > tonic::server::UnaryService<super::MsgCreateStableswapPool>
                    for CreateStableswapPoolSvc<T> {
                        type Response = super::MsgCreateStableswapPoolResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgCreateStableswapPool>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::create_stableswap_pool(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CreateStableswapPoolSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/osmosis.gamm.poolmodels.stableswap.v1beta1.Msg/StableSwapAdjustScalingFactors" => {
                    #[allow(non_camel_case_types)]
                    struct StableSwapAdjustScalingFactorsSvc<T: Msg>(pub Arc<T>);
                    impl<
                        T: Msg,
                    > tonic::server::UnaryService<
                        super::MsgStableSwapAdjustScalingFactors,
                    > for StableSwapAdjustScalingFactorsSvc<T> {
                        type Response = super::MsgStableSwapAdjustScalingFactorsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::MsgStableSwapAdjustScalingFactors,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::stable_swap_adjust_scaling_factors(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StableSwapAdjustScalingFactorsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: Msg> Clone for MsgServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Msg> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: Msg> tonic::server::NamedService for MsgServer<T> {
        const NAME: &'static str = "osmosis.gamm.poolmodels.stableswap.v1beta1.Msg";
    }
}
